
########################### Default parameters ##########################

baseURL = "https://cloudrefresh.io/"
languageCode = "en-us"
title = "CloudRefresh"

[params]
home = "Home"
# Meta data
description = "cloud"
# copyright
copyright = "Copyright 2020 &copy; [cloudrefresh](https://github.com/milldr/cloudrefresh/)"
# Google analytics
google_analytics_id = "UA-164491077-2"
# logo for header
logo = "images/logo.svg"


# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
URL = "s3://cloudrefresh.io?region=us-east-1"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf|woff|eot|xml)$"
cacheControl = "max-age=120, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true


#################################### Plugins ##########################################
[params.plugins]
  [[params.plugins.js]]
  URL = "css/jquery-3.5.1.min.js"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css2?family=Roboto&family=Work+Sans&display=swap"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css2?family=MuseoModerno:wght@800&display=swap"

###################################### Navigation ######################################
[menu]

  [[menu.main]]
  name = "Services"
  URL = "services"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

